In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('dataset/Churn_Modelling.csv')

In [6]:

X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [10]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X[:,1]

array([0., 1., 0., ..., 0., 0., 0.])

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
# X, y initial data
# test_size, percentage of data to be tested
# random_state, way to split data. (Random generator)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
print ("{} _ {}".format(len(X_train) , len(y_train)))

8000 _ 8000


In [14]:
print ("{} _ {}".format(len(X_test) , len(y_test)))

2000 _ 2000


In [15]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [18]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [19]:
# Initialising the ANN
classifier = Sequential()
# Adding the input layer and the first hidden layer
# Just your regular densely-connected NN layer. All neurons the same activation function
# can be defined activation functions by neuron
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
# optimizer Stochastic gradient descent = SGD
# loss = mean square error = mean_square_error
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
# batch size ( data to be trained at a time)
# nb_epoch (number of epochs needed to train the ANN)
classifier.fit(X_train, y_train, batch_size = 5, nb_epoch = 100)

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if sys.path[0] == '':
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.4836 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4272 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4218 - acc: 0.8001
Epoch 4/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4180 - acc: 0.8255
Epoch 5/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.4153 - acc: 0.8284
Epoch 6/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.4136 - acc: 0.8316
Epoch 7/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.4119 - acc: 0.8320
Epoch 8/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.4110 - acc: 0.8329
Epoch 9/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.4098 - acc: 0.8345
Epoch 10/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.4089 - acc: 0.8336

8000/8000 [==============================] - 1s 160us/step - loss: 0.4003 - acc: 0.8351
Epoch 83/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4006 - acc: 0.8344
Epoch 84/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4002 - acc: 0.8354
Epoch 85/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4001 - acc: 0.8349
Epoch 86/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.4003 - acc: 0.8355
Epoch 87/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.4005 - acc: 0.8346
Epoch 88/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3999 - acc: 0.8346
Epoch 89/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.4000 - acc: 0.8362
Epoch 90/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4000 - acc: 0.8359
Epoch 91/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3999 - acc: 0.8344
Epo

In [163]:
cm

array([[1532,   63],
       [ 254,  151]])

In [164]:
((cm[0][0]+cm[1][1])/(np.sum(cm)))*100

84.15